services:
  - type: web
    name: cprogrammingtest
    runtime: docker
    plan: free
    region: singapore
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: HOST
        value: 0.0.0.0
